### ISSUE TITLE
Bug Checkstyle - LineLength and FileTabCharacter

### ISSUE THREAD

**Issue by gemamb** [gemamb/VVS#12]
Modificación de estas dos reglas de manera errónea. De nuevo la definición de las mismas queda de la siguiente manera:

module name="FileTabCharacter"
property name="eachLine" value="true" 
module

module name="LineLength"
property name="max" value="80" 
module

**Comment by raquelLC** [comment]
Quedan 16 errores de tipo LineLength, pero se encuentran en los import de las clases BetService y BetServiceImpl
