### ISSUE TITLE
Bug Checkstyle - Names

### ISSUE THREAD

**Issue by gemamb** [gemamb/VVS#14]
A través de la herramienta checkstyle hemos detectado los siguientes errores en cuanto a las reglas de nombrado:

- ConstantName (5 errores)
- LocalVariableName (2 errores)
- MemberName (1 error)
- MethodName (4 errores)
- ParameterName (10 errores)
- TypeName (1 error)

**Comment by raquelLC** [comment]
Los errores de este tipo que se encuentran pertenecen a la clase es/udc/pa/pa001/apuestas/model/userservice/util/jcrypt.java.
Hemos decidido no resolverlos, ya que es una clase que no hemos implementado nosotras
