### ISSUE TITLE
Ruta para ficheros de pruebas

### ISSUE THREAD

**Issue by lauramcastro** [gemamb/VVS#6]
Habéis creado un paquete nuevo, `es.udc.pa.pa001.apuestas.test.VVS`, donde tenéis algunos ficheros de pruebas. La buena práctica es que todo fichero de pruebas se ubique en la ruta "gemela" a aquellas entidades que está probando, especialmente en el caso de pruebas unitarias. Las pruebas de integración se colocarían a nivel del paquete-padre que agrupa las unidades que se están integrando y así sucesivamente. No debería haber paquetes nuevos exclusivos del nivel de pruebas.

**Comment by raquelLC** [comment]
Tarea resuelta en los commits  9f2fd03a2536d5d9a227bc2b30d8f5af1b60ffa3 y 0f623411c3180d126bf5f889afdc6c160ade23ad
