### ISSUE TITLE
Modificación del comportamiento del modelo

### ISSUE THREAD

**Issue by gemamb** [gemamb/VVS#7]
Hemos comprobado que para el caso de uso CU-0x makeBet de BetService, hacíamos la validación de la cantidad de dinero a apostar en la capa web. Por lo tanto, modificaremos el comportamiento del modelo realizando dicha comprobación, y así posteriormente será probado.

**Comment by raquelLC** [comment]
Se ha añadido la excepción WrongQuantityException, que se lanza cuando el usuario intenta hacer una apuesta con una cantidad de dinero negativa.
